---
- hosts: webserver
  gather_facts: no
  tasks:
    - name: update ubuntu servers
      command: "sudo apt update"
    - name: Install python
      apt:
        name: python3-pip
        state: present
    - name: Install docker python module
      pip:
        name: docker
    - name: Install docker
      apt:
        name: docker.io
        state: present
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: create directory
      file:
        path: /home/ubuntu/jyoti
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        state: directory
    - name: copy the file to remot-server
      copy:
        src: /home/ubuntu/project/
        dest: /home/ubuntu/jyoti/
    - name: Build an image and push
      docker_image:
        name: jyotichaudhary90/web
        source: build
        build:
          path: /home/ubuntu/jyoti/
        state: present

    - name: Create container
      docker_container:
        name: staticweb
        image: jyotichaudhary90/web
        ports:
           - 80:80
        state: started
