---
- hosts: webserver
  gather_facts: no
  tasks:
    - name: update ubuntu servers
      command: "sudo apt update"
    - name: Install python
      apt:
        name: python3-pip
        state: present
    - name: Install docker python module
      pip:
        name: docker
    - name: Install docker
      apt:
        name: docker.io
        state: present
    - name: Install docker compose
      apt:
        name: docker-compose
        state: present
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Build an image and push
      docker_image:
        name: jyotichaudhary90/web:latest
        source: build
        build:
          path: /home/ubuntu/
        state: present
    - name: down container
      command: "docker compose down && docker compose up -d"
    
